spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: 959798309485-5v7rbndj62atpaqi28j2h2s6sls5f5rd.apps.googleusercontent.com
            clientSecret: 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